### ISSUE TITLE
Merge histograms option generates an error when using the histogrammer

### ISSUE THREAD

**Issue by danielguerrero** [UF-HH/bbbbAnalysis#28]
The message appears on the first quoted selection ( e.g. Btag3_VBFcateg_CR_110_Histogram):

terminate called after throwing an instance of 'std::runtime_error'
  what():  Bin corresponding to selection Btag3_VBFcateg_CR_110_Histogram not found in the cut histogram

The suspect is in here:
https://github.com/UF-HH/bbbbAnalysis/blob/master/src/AnalysisHelper.cc#L159

**Comment by l-cadamuro** [comment]
Update : this happens because the merge function was not updated to handle the histogram cut flow. The merged sample is created here:
https://github.com/UF-HH/bbbbAnalysis/blob/master/src/AnalysisHelper.cc#L1532
but the structure of the cut flow histogram is only created upon reading the file.
(at creation it is empty: https://github.com/UF-HH/bbbbAnalysis/blob/master/src/Sample.cc#L31
and it is initialised here: https://github.com/UF-HH/bbbbAnalysis/blob/master/src/Sample.cc#L116 )
but this second step cannot happen in the merge, because no tree is attached to the file.

I will try to make the cut histogram block independent so that it can be called there.

**Comment by l-cadamuro** [comment]
Fixed by modifying the AnalysisHelper and Sample classes to handle the histogram initialisation and the cut flow histograms upon merging.
