### ISSUE TITLE
Memory leak for histograms with systematics

### ISSUE THREAD

**Issue by fravera** [UF-HH/bbbbAnalysis#6]
When running the the fill_histogram there is a memory leak for plots with systematics.
The issue is caused in the analysis helper in the function prepareSamplesHistos().
Histograms  made by the loop on the "sample" and "selection" loops have the same hname:
hname = formHistoName (sampleName, selName, varName, currW.getSystName(isys));
Do we need both saved or we can get rid of one of them?

**Comment by l-cadamuro** [comment]
Hello Fabio,

I think that the issue comes from the fact that the same weight is assigned to both selections and samples in the cfg:

[selectionWeights]
selectionJet = bTagWeight_bJets_central, bTagWeight_cJets_central, bTagWeight_lightJets_central

[sampleWeights]
sig_Graviton_1000GeV = bTagWeight_bJets_central, bTagWeight_cJets_central, bTagWeight_lightJets_central
[...]

In this way the ``bTagWeight_bJets_central` weight, and its systematics afterwards, get applied to
1) all samples for the ``selectionJet`` selection
2) all ``sig_Graviton_1000GeV`` events regardless of the selections.

The way this is imagined is to have the possibility to apply specific weights for some specific selections (e.g. the b tag efficiency corrections once b tag cuts are applied) and also restrict to special weights for some particular processes (e.g. shape reweight for the signal).
In this case I would just remove all the weights from the ``sampleWeights`` list.

Do we need to put a specific check that there is no overlap between the two sets of weights passed?
